model:
  name: FerretNet-B-Median-3
  task: Synthetic image detection
  struct:
    name: Ferret
    in_channels: 3
    num_classes: 1
    dim: 96
    depths:
      - 2
      - 2
    lpd_func: median
    window_size: 3

data:
  train_set_dir: Dataset/progan-4cls
  test_set_dir: Dataset/ForenSynths
  dataset_type: SynDataset
  is_multi_loader: true
  class_to_idx:
  train_transforms:
    name: define_transforms
    kwargs:
      - type: RandomCrop
        size:
          - 224
          - 224
      - type: RandomHorizontalFlip
      - type: ToTensor
      - type: Normalize
        mean:
          - 0.48145466
          - 0.4578275
          - 0.40821073
        std:
          - 0.26862954
          - 0.26130258
          - 0.27577711
        inplace: true
  train_target_transforms:
  test_transforms:
    name: define_transforms
    kwargs:
      - type: CenterCrop
        size:
          - 256
          - 256
      - type: ToTensor
      - type: Normalize
        mean:
          - 0.48145466
          - 0.4578275
          - 0.40821073
        std:
          - 0.26862954
          - 0.26130258
          - 0.27577711
        inplace: true
  test_target_transforms:

optim:
  optimizer:
    name: Adam
    lr: 0.0002
    betas:
      - 0.937
      - 0.999
    weight_decay: 0.0005
  scheduler:

loss:
  loss_terms:
    name: BCEWithLogitsLoss

trainer:
  name: SynTrainer
  ckpt_dir: checkpoints
  resume_ckpt:
  batch_size: 32
  batch_size_per_gpu:
  batch_size_test: 32
  batch_size_per_gpu_test:
  num_workers_per_gpu: 8
  pin_memory: true
  scaler: native
  save_freq: 5
  sync_bn: false
  dist_bn:
  amp: true

logger:
  dir: logs/Train
  log_freq: 100
  logger_rank: 0

seed: 42
total_epochs: 100
warmup_epochs: 0
test_start_epoch: 50
